[book]
authors = ["Saverio Miroddi"]
language = "en"
multilingual = false
src = "src"
title = "Learn Bevy's ECS by ripping off someone else's project"
google_analytics_id = "UA-106009737-1"

[build]
build-dir = "docs"
